#!/usr/bin/sh
# |------------------------------------------|
# |               i3 wm Config               |
# |         Author: Francisco Suárez         |
# |       franksg88 [at] gmail [dot] com     |
# |                 Feb 2018                 |
# |                 Tarkin88                 |
# |------------------------------------------|

#Primary Key [default Windows key]
set $mod Mod4

# colors
set $backgr #333333
set $foregr #cccccc
set $accent #ebcb8b
set $urgent #CB5555

# default terminal
set $term termite

# resize
set $resize_value 2

# border
set $border_size 1

# colors settings
# class                   border    backgr    text    indicator   child_border
client.focused            $backgr   $backgr   $accent $accent   $accent
client.unfocused          $backgr   $backgr   $foregr $accent   $backgr
client.focused_inactive   $backgr   $backgr   $accent $accent   $accent
client.urgent             $backgr   $backgr   $accent $urgent   $urgent

#Font settings
font pango:monaco 9

# Border
new_window pixel $border_size
#new_window normal $border_size
new_float pixel $border_size

# Floating Settings
floating_modifier $mod


# start dmenu (a program launcher)
#bindsym $mod+d exec dmenu_run
#bindsym $mod+d exec rofi -show run
bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# start a terminal
bindsym $mod+Return exec $term

# kill focused window
bindsym $mod+Shift+q kill


# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# switch to workspace
bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace 1
bindsym $mod+Shift+2 move container to workspace 2
bindsym $mod+Shift+3 move container to workspace 3
bindsym $mod+Shift+4 move container to workspace 4
bindsym $mod+Shift+5 move container to workspace 5
bindsym $mod+Shift+6 move container to workspace 6
bindsym $mod+Shift+7 move container to workspace 7
bindsym $mod+Shift+8 move container to workspace 8
bindsym $mod+Shift+9 move container to workspace 9
bindsym $mod+Shift+0 move container to workspace 10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width $resize_value px or $resize_value ppt
        bindsym k resize grow height $resize_value px or $resize_value ppt
        bindsym l resize shrink height $resize_value px or $resize_value ppt
        bindsym semicolon resize grow width $resize_value px or $resize_value ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width $resize_value px or $resize_value ppt
        bindsym Down resize grow height $resize_value px or $resize_value ppt
        bindsym Up resize shrink height $resize_value px or $resize_value ppt
        bindsym Right resize grow width $resize_value px or $resize_value ppt

        # back to normal: Enter or Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

bindsym $mod+r mode "resize"

# similar behavior to windows alt + tab on workspaces
bindsym $mod+Tab workspace back_and_forth

bindsym Print exec --no-startup-id "scrot '%S.png' -e 'mv $f $$(xdg-user-dir PICTURES)/Screenshots/screenshot-%d-%m-%y_%H-%M-%S.png \; viewnior $$(xdg-user-dir PICTURES)/Screenshots/screenshot-%d-%m-%y_%H-%M-%S.png'"


# brightness dec
bindsym XF86MonBrightnessDown exec xbacklight -dec 15

# brightness inc
bindsym XF86MonBrightnessUp exec xbacklight -inc 15

# Previous
bindsym XF86AudioPrev exec "mpc prev"

# Next
bindsym XF86AudioNext exec "mpc next"

# Play/Pause
bindsym XF86AudioPlay exec "mpc toggle"

# Play/Pause
bindsym XF86AudioStop  exec mpc stop
# Mute
bindsym XF86AudioMute exec "amixer -q sset Master toggle"
# Volume down
bindsym XF86AudioLowerVolume exec "amixer -q set Master 3%- unmute"
# Volume up
bindsym XF86AudioRaiseVolume exec "amixer -q set Master 3%+ unmute"



# focus rules
for_window [window_role="pop-up"] floating enable
for_window [window_role="bubble"] floating enable
for_window [window_role="task_dialog"] floating enable
for_window [window_role="Preferences"] floating enable
for_window [window_type="dialog"] floating enable
for_window [window_type="menu"] floating enable
for_window [class="Galculator"] floating enable border normal
for_window [class="GParted"] floating enable border normal
for_window [class="Pavucontrol"] floating enable border normal
for_window [class="Lxappearance"] floating enable border normal
for_window [class="Gnome-mplayer"] floating enable border normal
for_window [title="^ncmpcpp$"] floating enable border normal
for_window [title="^htop$"] floating enable border normal
for_window [title="^alsamixer$"] floating enable border normal
for_window [title="^pacli$"] floating enable border normal

# autorun
exec --no-startup-id ~/.config/i3/autostart.sh
