#!/usr/bin/sh

BG="#E8DFD6"
FG="#E8DFD6"
CC="#F3D5C9"
HBC="#009688"
HC="#ef9a9a"

# black
color0="#37413F"
color8="#4B5755"

# red
color1="#F99595"
color9="#F3D5C9"

# green
color2="#7CBF9E"
color10="#A2D9B1"

# yellow
color3="#E5C078"
color11="#F9D48C"

# blue
color4="#7BBAC7"
color12="#DFF0EB"

# magenta
color5="#FF5879"
color13="#FF99A1"

# cyan
color6="#62BDB3"
color14="#9ED9D8"

# white
color7="#F2F1B9"
color15="#F6F6C9"
