" ------------------------------

syntax on
set number

" Enable filetype plugins
filetype plugin on
filetype indent on

" Set to auto read when a file is changed from the outside
set autoread

" Enable intentation lines
set list
set listchars=tab:\┆\ 

" Indentation
set noexpandtab
set tabstop=4
set shiftwidth=4

" Disable backups
set nobackup
set nowritebackup
set noswapfile
set noundofile

" Turn on the WiLd menu
set wildmenu

"Always show current position
set ruler

" Highlight search results
set hlsearch

" Makes search act like search in modern browsers
set incsearch 

" Show matching brackets when text indicator is over them
set showmatch 


" Set utf8 as standard encoding and en_US as the standard language
set encoding=utf8

