#!/usr/bin/sh

[global]
    alignment = right
    allow_markup = yes
    bounce_freq = 1
    browser = /usr/bin/chromium
    dmenu = /usr/bin/dmenu -p dunst:
    follow = none
    font = monaco (TTF) 11
    format = "<b>%s</b>\n%b"
    # geometry [{width}]x{height}][+/-{x}+/-{y}]
    geometry = "0-15+20"
    history_length = 30
    horizontal_padding = 40
    idle_threshold = 120
    ignore_newline = no
    indicate_hidden = yes
    line_height = 0
    monitor = 0
    padding = 20
    separator_color = frame
    separator_height = 2
    show_age_threshold = 60
    show_indicators = yes
    shrink = no
    sort = yes
    startup_notification = yes
    sticky_history = yes
    transparency = 10
    word_wrap = yes

[frame]
    width = 1
    color = "#434343"

[shortcuts]
    close = mod4+z
    #close_all = mod4+ctrl+x
    history = mod4+grave
    context = ctrl+shift+period

[urgency_low]
    background = "#278276"
    foreground = "#FFFFFF"
    timeout = 10

[urgency_normal]
    background = "#278276"
    foreground = "#FFFFFF"
    timeout = 20

[urgency_critical]
    background = "#801515"
    foreground = "#D46A6A"
    timeout = 0
