#!/usr/bin/sh

[options]
font = Monaco 11
audible_bell = true
visible_bell = false
dynamic_title = true
urgent_on_bell = true
clickable_url = true
geometry = 820x520
# "system", "on" or "off"
cursor_blink = system
# "block", "underline" or "ibeam"
cursor_shape = underline
# $BROWSER is used by default
browser = google-chrome-stable

[colors]
background = #344042
foreground = #E8DFD6
cursor     = #F3D5C9

# black
color0=#37413F
color8=#4B5755

# re
color1=#F99595
color9=#F3D5C9

# green
color2=#7CBF9E
color10=#A2D9B1

# yellow
color3=#E5C078
color11=#F9D48C

# blue
color4=#7BBAC7
color12=#DFF0EB

# magenta
color5=#FF5879
color13=#FF99A1

# cyan
color6=#62BDB3
color14=#9ED9D8

# white
color7=#F2F1B9
color15=#F6F6C9
