#!/usr/bin/sh
[options]
font = Monaco 11
audible_bell = true
visible_bell = false
dynamic_title = true
urgent_on_bell = true
clickable_url = true
geometry = 890x600
# "system", "on" or "off"
cursor_blink = system
# "block", "underline" or "ibeam"
cursor_shape = underline
# $BROWSER is used by default
browser = google-chrome-stable

[colors]
background = #2d2d2d
foreground = #cccccc
cursor     = #b3bfc7
color0     = #272822
color8     = #37474f
color1     = #ff9800
color9     = #ffa74d
color2     = #8bc34a
color10    = #9ccc65
color3     = #ffc107
color11    = #ffa000
color4     = #03a9f4
color12    = #81d4fa
color5     = #ea427b
color13    = #ad1457
color6     = #009688
color14    = #26a69a
color7     = #cfd8dc
color15    = #eceff1
