#!/bin/sh
# |------------------------------------------|
# |                  i3 Config               |
# |         Author: Francisco Suárez         |
# |       franksg88 [at] gmail [dot] com     |
# |               December 2017              |
# |------------------------------------------|

#Primary Key [default Windows key]
set $mod Mod4

# Global Variables
# colors
set $backgr #282A36
set $foregr #E3E3E3
set $accent #29C1B6
set $urgent #CB5555

# gaps
set $gaps_inner 3
set $gaps_outer 3
# resize
set $resize_value 2
# border
set $border_size 2
# default terminal
set $term termite
#Font settings
font pango:monaco 9

# Floating Settings
floating_modifier $mod

# kill focused window
bindsym $mod+Shift+q kill

# Launcher settings
#bindsym $mod+d exec "dmenu_run -i -p 'Launch' -fn '8x11' -nb '$backgr' -nf '$foregr' -sb '$backgr' -sf '$accent'"
bindsym $mod+d exec rofi -show run

# Terminal
bindsym $mod+Return exec $term

# Border
new_window pixel $border_size
#new_window normal $border_size
new_float pixel $border_size

# fix graphics glitch
#new_window none

# Follow mouse
focus_follows_mouse no|

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

bindsym $mod+q split toggle

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+Shift+space focus child

# switch to workspace
bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace 1
bindsym $mod+Shift+2 move container to workspace 2
bindsym $mod+Shift+3 move container to workspace 3
bindsym $mod+Shift+4 move container to workspace 4
bindsym $mod+Shift+5 move container to workspace 5
bindsym $mod+Shift+6 move container to workspace 6
bindsym $mod+Shift+7 move container to workspace 7
bindsym $mod+Shift+8 move container to workspace 8
bindsym $mod+Shift+9 move container to workspace 9
bindsym $mod+Shift+0 move container to workspace 10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'Bye bye dude.' -b 'EXIT' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width $resize_value px or $resize_value ppt
        bindsym k resize grow height $resize_value px or $resize_value ppt
        bindsym l resize shrink height $resize_value px or $resize_value ppt
        bindsym semicolon resize grow width $resize_value px or $resize_value ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width $resize_value px or $resize_value ppt
        bindsym Down resize grow height $resize_value px or $resize_value ppt
        bindsym Up resize shrink height $resize_value px or $resize_value ppt
        bindsym Right resize grow width $resize_value px or $resize_value ppt

        # back to normal: Enter or Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

bindsym $mod+r mode "resize"

#custom byndsym

# similar behavior to windows alt + tab on workspaces
bindsym $mod+Tab workspace back_and_forth
#Lock screen
bindsym $mod+x exec "~/.config/bash_scripts/lock.sh -l dimblur"
#launch ranger [CLI file manager ]
bindsym $mod+F1 exec $term -e "ranger"
# brightness dec
#bindsym XF86MonBrightnessDown exec xbacklight -dec 15
# brightness inc
#bindsym XF86MonBrightnessUp exec xbacklight -inc 15
# Previous
bindsym XF86AudioPrev exec "dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous"
# Next
bindsym XF86AudioNext exec "dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next"
# Play/Pause
bindsym XF86AudioPlay exec "dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause"

# Mute
bindsym XF86AudioMute exec "amixer -q sset Master toggle"
# Volume down
bindsym XF86AudioLowerVolume exec "amixer -q set Master 3%- unmute"
# Volume up
bindsym XF86AudioRaiseVolume exec "amixer -q set Master 3%+ unmute"

# focus rules
for_window [window_role="pop-up"] floating enable
for_window [window_role="bubble"] floating enable
for_window [window_role="task_dialog"] floating enable
for_window [class="Galculator"] floating enable border normal
for_window [window_role="Preferences"] floating enable
for_window [class="Nitrogen"] floating enable border normal
for_window [window_type="dialog"] floating enable
for_window [window_type="oblogout"] floating enable
for_window [window_type="menu"] floating enable
for_window [class="Vlc"] floating enable border pixel 1
for_window [class="Mplayer"] floating enable border pixel 1
for_window [class="GParted"] floating enable border normal
for_window [class="Pavucontrol"] floating enable border normal
for_window [class="Lxappearance"] floating enable border normal


# colors settings
# class                   border    backgr    text    indicator   child_border
client.focused            $backgr   $backgr   $accent $accent   $accent
client.unfocused          $backgr   $backgr   $foregr $accent   $backgr
client.focused_inactive   $backgr   $backgr   $accent $accent   $accent
client.urgent             $backgr   $backgr   $accent $urgent   $urgent

# autorun
exec --no-startup-id ~/.config/bash_scripts/autostart.sh


#############################
### settings for i3-gaps: ###
#############################

# Set inner/outer gaps

gaps inner $gaps_inner
gaps outer $gaps_outer

# Additionally, you can issue commands with the following syntax. This is useful to bind keys to changing the gap size.
# gaps inner|outer current|all set|plus|minus <px>
# gaps inner all set 10
# gaps outer all plus 5

# Smart gaps (gaps used if only more than one container on the workspace)
smart_gaps on

# Smart borders (draw borders around container only if it is not the only container on this workspace) 
# on|no_gaps (on=always activate and no_gaps=only activate if the gap size to the edge of the screen is 0)
smart_borders on

# Press $mod+Shift+g to enter the gap mode. Choose o or i for modifying outer/inner gaps. Press one of + / - (in-/decrement for current workspace) or 0 (remove gaps for current workspace). If you also press Shift with these keys, the change will be global for all workspaces.
set $mode_gaps Gaps: (o) outer, (i) inner
set $mode_gaps_outer Outer Gaps: +|-|0 (local), Shift + +|-|0 (global)
set $mode_gaps_inner Inner Gaps: +|-|0 (local), Shift + +|-|0 (global)
bindsym $mod+Shift+g mode "$mode_gaps"

mode "$mode_gaps" {
        bindsym o      mode "$mode_gaps_outer"
        bindsym i      mode "$mode_gaps_inner"
        bindsym Return mode "default"
        bindsym Escape mode "default"
}
mode "$mode_gaps_inner" {
        bindsym plus  gaps inner current plus 5
        bindsym minus gaps inner current minus 5
        bindsym 0     gaps inner current set 0

        bindsym Shift+plus  gaps inner all plus 5
        bindsym Shift+minus gaps inner all minus 5
        bindsym Shift+0     gaps inner all set 0

        bindsym Return mode "default"
        bindsym Escape mode "default"
}
mode "$mode_gaps_outer" {
        bindsym plus  gaps outer current plus 5
        bindsym minus gaps outer current minus 5
        bindsym 0     gaps outer current set 0

        bindsym Shift+plus  gaps outer all plus 5
        bindsym Shift+minus gaps outer all minus 5
        bindsym Shift+0     gaps outer all set 0

        bindsym Return mode "default"
        bindsym Escape mode "default"
}