#!/usr/bin/sh
# |------------------------------------------|
# |               i3 wm Config               |
# |         Author: Francisco Suárez         |
# |            github: tarkin88              |
# |                 Jun 2019                 |
# |------------------------------------------|

# ================================= VARIABLES ====================================================
#
#Primary Key [default Windows key]
set $mod Mod4

BACKGROUND
FOREGROUND
ACCENT
URGENT

# how to apply colors (uncomment)
# set $backgr COLOR
# set $foregr COLOR
# set $accent COLOR
# set $urgent COLOR

# default terminal
set $term alacritty

# secondary 
set $term2 termite

# resize
set $resize_value 4

# border
set $border_size 1

set $BROWSER google-chrome

# ================================= STYLES ====================================================
#
# colors settings
# class                   border    backgr    text    indicator   child_border
client.focused            $backgr   $backgr   $accent $accent   $accent
client.unfocused          $backgr   $backgr   $foregr $accent   $backgr
client.focused_inactive   $backgr   $backgr   $accent $accent   $accent
client.urgent             $backgr   $backgr   $accent $urgent   $urgent

#Font settings
font pango:hack 11

#Disable  mouse focus
focus_follows_mouse no

## set workspaces
set $ws1  "1: 1"
set $ws2  "2: 2"
set $ws3  "3: 3"
set $ws4  "4: 4"
set $ws5  "5: 5"
set $ws6  "6: 6"
set $ws7  "7: 7"
set $ws8  "8: 8"

# Border
new_window pixel $border_size

#new_window normal $border_size
new_float pixel $border_size

# Floating Settings
floating_modifier $mod


# start dmenu (a program launcher)
# ================================= SHORTCUTS ====================================================
#
bindsym $mod+d exec rofi -show run

# start a terminal
bindsym $mod+Return exec $term

# start a secondary terminal
bindsym $mod+Shift+Return exec $term2

# kill focused window
bindsym $mod+Shift+q kill

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
#bindsym $mod+Shift+j move left
#bindsym $mod+Shift+k move down
#bindsym $mod+Shift+l move up
#bindsym $mod+Shift+semicolon move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# switch to workspace
bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace 1
bindsym $mod+Shift+2 move container to workspace 2
bindsym $mod+Shift+3 move container to workspace 3
bindsym $mod+Shift+4 move container to workspace 4
bindsym $mod+Shift+5 move container to workspace 5
bindsym $mod+Shift+6 move container to workspace 6
bindsym $mod+Shift+7 move container to workspace 7
bindsym $mod+Shift+8 move container to workspace 8
bindsym $mod+Shift+9 move container to workspace 9
bindsym $mod+Shift+0 move container to workspace 10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        bindsym Left resize shrink width $resize_value px or $resize_value ppt
        bindsym Down resize grow height $resize_value px or $resize_value ppt
        bindsym Up resize shrink height $resize_value px or $resize_value ppt
        bindsym Right resize grow width $resize_value px or $resize_value ppt
        # back to normal: Enter or Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

# ============================= CUSTOM SHORTCUTS ====================================================
#
bindsym $mod+r mode "resize"
# similar behavior to windows alt + tab on workspaces
bindsym $mod+Tab workspace back_and_forth
#ScreenShots
bindsym Print exec ~/.bin/rofr.sh -s
# File manager
bindsym $mod+F1 workspace 4; layout tabbed; exec [ $(ps h -C pcmanfm | wc -l) = 0 ] && /usr/bin/pcmanfm
# Ranger
bindsym $mod+F2 workspace 4; layout tabbed; exec [ $(ps h -C ranger | wc -l) = 0 ] && $term -e "ranger"
# CLI Media Player
bindsym $mod+F4; exec $term -e "ncmpcpp"
# Browser
bindsym $mod+F3 workspace 2; layout tabbed; exec [ $(ps h -C $BROWSER | wc -l) = 0 ] && $BROWSER
# brightness dec
bindsym XF86MonBrightnessDown exec xbacklight -dec 15
# brightness inc
bindsym XF86MonBrightnessUp exec xbacklight -inc 15
# Previous
bindsym XF86AudioPrev exec playerctl -p spotify previous
# Next
bindsym XF86AudioNext exec playerctl -p spotify next
# Play/Pause
bindsym XF86AudioPlay exec playerctl -p spotify play-pause
# Play/Pause
bindsym XF86AudioStop  exec playerctl -p spotify stop
# Mute
bindsym XF86AudioMute exec "amixer -q sset Master toggle"
# Volume down
bindsym XF86AudioLowerVolume exec "amixer -q set Master 3%- unmute"
# Volume up
bindsym XF86AudioRaiseVolume exec "amixer -q set Master 3%+ unmute"
# exit 
bindsym $mod+Shift+x exec ~/.bin/rofr.sh -l
#clipboard
bindsym $mod+Shift+h exec ~/.bin/rofr.sh -c
# Calculator
bindsym $mod+q exec ~/.bin/rofr.sh -q
# Windows
bindsym $mod+Shift+Tab exec ~/.bin/rofr.sh -w
# lockscreen
bindsym $mod+shift+l exec betterlockscreen --lock dimblur
# Bitwarden
bindsym $mod+Shift+b exec ~/.bin/rofr.sh -b

# ================================= RULES ====================================================
#
for_window [window_role="pop-up"] floating enable
for_window [window_role="bubble"] floating enable
for_window [window_role="task_dialog"] floating enable
for_window [window_role="Preferences"] floating enable
for_window [window_type="dialog"] floating enable
for_window [window_type="menu"] floating enable
for_window [class="GParted"] floating enable border normal
for_window [class="Gnome-mplayer"] floating enable border normal
for_window [title="^ncmpcpp$"] floating enable border normal
for_window [title="^spotify$"] floating enable border normal
for_window [title="^htop$"] floating enable border normal
for_window [title="^alsamixer$"] floating enable border normal
for_window [class=Viewnior|Galculator|feh|Audacious|File-roller|Lxappearance|Lxtask|Pavucontrol] floating enable

# ================================= AUTORUN ====================================================
#
exec --no-startup-id ~/.bin/autostart.sh
