#!/usr/bin/sh
# |------------------------------------------|
# |               i3 wm Config               |
# |         Author: Francisco Suárez         |
# |            github: tarkin88              |
# |               March 2020                 |
# |------------------------------------------|

# ================================= VARIABLES ====================================================
#
#Primary Key [default Windows key]
set $mod Mod4

BACKGROUND
FOREGROUND
ACCENT
URGENT

# how to apply colors (uncomment)
# set $backgr COLOR
# set $foregr COLOR
# set $accent COLOR
# set $urgent COLOR

# default terminal
set $term kitty

# resize
set $resize_value 5

# border
set $border_size 1

set $BROWSER google-chrome

# GAPS settings
# i3-gaps from https://github.com/Airblader/i3
# Disable window titlebars entirely
for_window [class="^.*"] border pixel 3

# Set inner/outer gaps
gaps inner 8
gaps outer 4
# Smart gaps (gaps used if only more than one container on the workspace)
smart_gaps on
# Smart borders (draw borders around container only if it is not the only container on this workspace)
# on|no_gaps (on=always activate and no_gaps=only activate if the gap size to the edge of the screen is 0)
smart_borders on

# ================================= STYLES ====================================================
#
# colors settings
# class                   border    backgr    text    indicator   child_border
client.focused            $backgr   $backgr   $accent $accent   $accent
client.unfocused          $backgr   $backgr   $foregr $accent   $backgr
client.focused_inactive   $backgr   $backgr   $accent $accent   $accent
client.urgent             $backgr   $backgr   $accent $urgent   $urgent

#Font settings
font pango:hack 11

#Disable  mouse focus
focus_follows_mouse no

## set workspaces
set $ws1  "1: 1"
set $ws2  "2: 2"
set $ws3  "3: 3"
set $ws4  "4: 4"
set $ws5  "5: 5"
set $ws6  "6: 6"
set $ws7  "7: 7"
set $ws8  "8: 8"

# Border
new_window pixel $border_size

#new_window normal $border_size
new_float pixel $border_size

# Floating Settings
floating_modifier $mod


# start dmenu (a program launcher)
# ================================= SHORTCUTS ====================================================
#
bindsym $mod+d exec rofi -show run

# start a terminal
bindsym $mod+Return exec $term

# start a secondary terminal
bindsym $mod+Shift+Return exec $term2

# kill focused window
bindsym $mod+Shift+q kill

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
#bindsym $mod+Shift+j move left
#bindsym $mod+Shift+k move down
#bindsym $mod+Shift+l move up
#bindsym $mod+Shift+semicolon move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# switch to workspace
bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace 1
bindsym $mod+Shift+2 move container to workspace 2
bindsym $mod+Shift+3 move container to workspace 3
bindsym $mod+Shift+4 move container to workspace 4
bindsym $mod+Shift+5 move container to workspace 5
bindsym $mod+Shift+6 move container to workspace 6
bindsym $mod+Shift+7 move container to workspace 7
bindsym $mod+Shift+8 move container to workspace 8
bindsym $mod+Shift+9 move container to workspace 9
bindsym $mod+Shift+0 move container to workspace 10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        bindsym Left resize shrink width $resize_value px or $resize_value ppt
        bindsym Down resize grow height $resize_value px or $resize_value ppt
        bindsym Up resize shrink height $resize_value px or $resize_value ppt
        bindsym Right resize grow width $resize_value px or $resize_value ppt
        # back to normal: Enter or Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

# ============================= CUSTOM SHORTCUTS ====================================================
#
bindsym $mod+r mode "resize"
# similar behavior to windows alt + tab on workspaces
bindsym $mod+Tab workspace back_and_forth
#ScreenShots
bindsym Print exec ~/.bin/rofr.sh -s
# File manager
bindsym $mod+F1 exec [ $(ps h -C pcmanfm | wc -l) = 0 ] && /usr/bin/pcmanfm
# Ranger
bindsym $mod+F2 exec [ $(ps h -C ranger | wc -l) = 0 ] && $term -e "ranger"
# CLI Media Player
bindsym $mod+F4; exec $term -e "ncmpcpp"
# Browser
bindsym $mod+F3 workspace 2; layout tabbed; exec [ $(ps h -C $BROWSER | wc -l) = 0 ] && $BROWSER
# brightness dec
bindsym XF86MonBrightnessDown exec xbacklight -dec 15
# brightness inc
bindsym XF86MonBrightnessUp exec xbacklight -inc 15
# Previous
#bindsym XF86AudioPrev exec playerctl -p spotify previous
bindsym XF86AudioPrev exec "mpc prev; sleep 0.5s; sh -c '~/.bin/ncmpcppp_cover.sh'"
# Next
#bindsym XF86AudioNext exec playerctl -p spotify next
bindsym XF86AudioNext exec "mpc next; sleep 0.5s; sh -c '~/.bin/ncmpcppp_cover.sh'"
# Play/Pause
#bindsym XF86AudioPlay exec playerctl -p spotify play-pause
bindsym XF86AudioPlay exec "mpc toggle; sleep 0.5s; sh -c '~/.bin/ncmpcppp_cover.sh'"
# STOP
#bindsym XF86AudioStop  exec playerctl -p spotify stop
bindsym XF86AudioStop  exec "mpc stop"
# Mute
bindsym XF86AudioMute exec "amixer -q sset Master toggle"
# Volume down
bindsym XF86AudioLowerVolume exec "amixer -q set Master 3%- unmute"
# Volume up
bindsym XF86AudioRaiseVolume exec "amixer -q set Master 3%+ unmute"
# exit
bindsym $mod+Shift+x exec ~/.bin/rofr.sh -l
#clipboard
bindsym $mod+Shift+h exec ~/.bin/rofr.sh -c
# Calculator
bindsym $mod+q exec ~/.bin/rofr.sh -q
# Windows
bindsym $mod+Shift+Tab exec ~/.bin/rofr.sh -w
# lockscreen
bindsym $mod+shift+l exec betterlockscreen --lock dimblur
# Bitwarden
bindsym $mod+Shift+b exec ~/.bin/rofr.sh -e

# ================================= GAPS ====================================================

# Press $mod+Shift+g to enter the gap mode. Choose o or i for modifying outer/inner gaps.
# Press one of + / - (in-/decrement for current workspace) or 0 (remove gaps for current workspace). If you also press Shift with these keys, the change will be global for all workspaces.
set $mode_gaps Gaps: (o) outer, (i) inner
set $mode_gaps_outer Outer Gaps: +|-|0 (local), Shift + +|-|0 (global)
set $mode_gaps_inner Inner Gaps: +|-|0 (local), Shift + +|-|0 (global)
bindsym $mod+Shift+g mode "$mode_gaps"

mode "$mode_gaps" {
        bindsym o      mode "$mode_gaps_outer"
        bindsym i      mode "$mode_gaps_inner"
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

mode "$mode_gaps_inner" {
        bindsym plus  gaps inner current plus 5
        bindsym minus gaps inner current minus 5
        bindsym 0     gaps inner current set 0

        bindsym Shift+plus  gaps inner all plus 5
        bindsym Shift+minus gaps inner all minus 5
        bindsym Shift+0     gaps inner all set 0

        bindsym Return mode "default"
        bindsym Escape mode "default"
}
mode "$mode_gaps_outer" {
        bindsym plus  gaps outer current plus 5
        bindsym minus gaps outer current minus 5
        bindsym 0     gaps outer current set 0

        bindsym Shift+plus  gaps outer all plus 5
        bindsym Shift+minus gaps outer all minus 5
        bindsym Shift+0     gaps outer all set 0

        bindsym Return mode "default"
        bindsym Escape mode "default"
}

# ================================= RULES ====================================================
#
for_window [window_role="pop-up"] floating enable
for_window [window_role="bubble"] floating enable
for_window [window_role="task_dialog"] floating enable
for_window [window_role="Preferences"] floating enable
for_window [window_type="dialog"] floating enable
for_window [window_type="menu"] floating enable
for_window [class="GParted"] floating enable border normal
for_window [class="Gnome-mplayer"] floating enable border n
for_window [title="^alsamixer$"] floating enable border normal
for_window [class=Viewnior|Galculator|feh|Audacious|File-roller|Lxappearance|Lxtask|Pavucontrol] floating enable

# ================================= AUTORUN ====================================================
#
exec --no-startup-id ~/.bin/autostart.sh
