source ~/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle pip
antigen bundle command-not-found
antigen bundle git-flow-avh
antigen bundle zdharma/fast-syntax-highlighting

#POWERLEVEL9K_INSTALLATION_PATH=$ANTIGEN_BUNDLES/bhilburn/powerlevel9k
#antigen theme bhilburn/powerlevel9k powerlevel9k

# Load the theme.
antigen bundle denysdovhan/spaceship-prompt

# Tell Antigen that you're done.
antigen apply

export PATH=$HOME/.bin:$HOME/.bin/yarn/bin:$PATH
export EDITOR='vim'


# Android Variables
#export ANDROID_HOME=/opt/android-sdk
#PATH=$PATH:$ANDROID_HOME/tools
#PATH=$PATH:$ANDROID_HOME/platform-tools  



setopt AUTO_CD # No cd needed to change directories
setopt BANG_HIST # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST # Expire duplicate entries first when trimming history.
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS # Delete old recorded entry if new entry is a duplicate.
setopt HIST_IGNORE_DUPS # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_SPACE # Don't record an entry starting with a space.
setopt HIST_REDUCE_BLANKS # Remove superfluous blanks before recording entry.
setopt HIST_SAVE_NO_DUPS # Don't write duplicate entries in the history file.
setopt INC_APPEND_HISTORY # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY # Share history between all sessions.

SPACESHIP_PROMPT_FIRST_PREFIX_SHOW=true
